# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pincode',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
